//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstProject
{
    using System;
    
    public enum Classification : byte
    {
        Gold = 1,
        Silver = 2,
        Platinum = 3
    }
}
